### PR TITLE
Fix proxy config not echoed to config UI and not read during upload/download

### PR DESCRIPTION
**Pull request by haku**
Due to missing getters on S3Profile, configured proxies were not echoed to fields in config UI, so saving subsequent config changes erased proxy settings.
Fix proxies not using during config testing while editing in config UI.
Fix proxy settings not being passed to AbstractS3Callable, thus were not being used during actual file transfer.

### CODE REVIEW

**Comment by JoeNunnelley** [comment]
Hi, I recently pulled down this fork and applied it to my jenkins server to fix an issue we were having with our proxy settings not being honored by the released plugin.  It solved the problems I was having and I'm now able to upload files to S3.  Will this get merged into the main line soon? It would be super great to be able to use a released version of this plugin.  I'd be happy to help with any merging that may be required.

**Comment by JoeNunnelley** [comment]
any update on merging this in?

**Comment by ogg1e** [comment]
Is anyone going to look at this? I need the proxy settings as well.

**Comment by tjnicholas** [comment]
Proxy support remains broken... /cc @zl4bv

**Comment by ebrahim-moshaya** [comment]
please merge this pull request!!

**Comment by Jimilian** [comment]
@haku Thanks for your PR!
Proxy was fixed in another PR as well. Now plugin are using proxy settings from Jenkins.

**Pull request closed without merging**
