### PR TITLE
Support for workflow plugin

### PR DESCRIPTION
**Pull request by Jimilian**
This PR supports workflow plugin for S3-plugin. More information about workflow plugin [is here](https://github.com/jenkinsci/workflow-plugin).

Also I updated Jenkins version to 1.609.3.

This PR based on https://github.com/jenkinsci/s3-plugin/pull/79

### CODE REVIEW

**Comment by peternijssen** [comment]
Would love to see support for the workflow plugin. @ndeloof any chance this can get merged?

**Comment by ndeloof** [comment]
I'm not maintainer on this plugin (afaik there is none) would you like to take ownership ?

**Comment by peternijssen** [comment]
Ah okay. Just noticed you accepted the last merge requests that's why I thought you maintained it. I can't maintain. To less knowledge of Jenkins plugins and Java :(

**Comment by Jimilian** [comment]
@peternijssen If you are going to build S3-plugin Workflow/Pipeline support, it's better to use https://github.com/jenkinsci/s3-plugin/pull/82. It contains all changes and backport capability. It works pretty good on Linux, but still have sometimes issue on Windows (we didn't finish our investigation, it could be issue in Multipart Uploading, our environment, S3 itself or all together :) )
@ndeloof I can take ownership, but I didn't have such experience before.

**Pull request closed without merging**
