### PR TITLE
Fix non-flattened pushing of artefacts 

### PR DESCRIPTION
**Pull request by thors**
Using the S3 plugin experimentally, I noticed some bugs related to push to / pull from S3 buckets without flattening. 

Following issues were fixed:
- File masks like "dist/*, data.txt" lead to "java.lang.StringIndexOutOfBoundsException: String index out of range:"
- files "dist/data.txt" and "data.txt" are both stored as "data.txt"

### CODE REVIEW

**Comment by rdesgroppes** [comment]
Thorsten, they'd likely reject your changes. You'd better:
- removing dead code rather than keeping it commented: it's git's history role
- minding the sibling indentation (people would have to re-indent next time they edit it)
- undoing whitespace-only changes (unrelated lines got modified)
- removing comments on your changes (w/ or w/o your name): it's git's comment role

**Comment by thors** [comment]
@rdesgroppes Thanks for the feedback, I will adjust the branch accordingly and prepare a new pull request. I will keep this pull request to collect further feedback and will cancel it when placing the new request (assuming this one isn't unexpectedly accepted in the meantime)

**Comment by thors** [comment]
@rdesgroppes I added two commits to apply the fixes you proposed. I didn't know this will automatically be included to the same pull request...

**Comment by hubx** [comment]
I'm also interested in this. Any chance this gets merged soon?

**Comment by liyaka** [comment]
I'm also interested in this fix, any plans to fix the conflicts and merge it

**Comment by kashiif** [comment]
+1

**Comment by Jimilian** [comment]
I merged https://github.com/jenkinsci/s3-plugin/pull/82. So, I'm closing this PR. 
Thanks, @thors

**Pull request closed without merging**
