### PR TITLE
Workflow plugin, Retries for downloading, Several profiles, Fixed flatten directories, Uploading and downloading for big files, Excludes

### PR DESCRIPTION
**Pull request by Jimilian**
In this PR I made several changes:
* Add retries for downloading
* Moved retries options to advance (and renamed it, so, you need to update values after updating plugin)
* Cleanup code a little bit

So, it's my last PR for s3-plugin in this year. It based on https://github.com/jenkinsci/s3-plugin/pull/81. It means that this PR contains all changes from:
* https://github.com/jenkinsci/s3-plugin/pull/78
* https://github.com/jenkinsci/s3-plugin/pull/79
* https://github.com/jenkinsci/s3-plugin/pull/80
* https://github.com/jenkinsci/s3-plugin/pull/81

More detail:
* Uploading and downloading files more than 5GB
* Flatten directories
* Excludes for downloading and uploading
* Several profiles
* Retries for downloading
* Workflow plugin support
* Fix proxy for downloading and uploading (Also, I removed it from UI, now it uses only Jenkins proxy setup)

### CODE REVIEW

**Comment by josb** [comment]
@ndeloof: This is a very useful PR. Any chance we can get it validated and merged, please?

**Comment by ndeloof** [comment]
@josb I'm not a maintainer on this plugin. Not sure there's an active one. Feel free to ask for ownership if you are volunteer

**Comment by josb** [comment]
@ndeloof thanks!

**Comment by Jimilian** [comment]
@josb At here.com we are using this plugin in highload environment (~300 slaves, ~1300 executors). And it works. So, feel free to compile your own S3-plugin with this changes ;)
@ndeloof How to take a ownership? My company are interested in this very much, because we are using this plugin everywhere.

Also, it looks like @jenkinsadmin stuck and didn't send feedback to this PR.

**Comment by ndeloof** [comment]
@Jimilian just ask on jenkins-dev mailing list

**Comment by josb** [comment]
@Jimilian thanks, that's exactly what I did :) It appears to work well; thanks for adding these changes! I look forward to seeing them land.

**Comment by romanblachman** [comment]
@Jimilian does your PR by any chance supports uploading artifacts from Jenkins slaves? I know that due to serialization issue with MetadataPair this fails in the master stable version. https://issues.jenkins-ci.org/browse/JENKINS-33088

**Comment by Jimilian** [comment]
@romanblachman, I checked last version with some dumb metadata ("Key"/"Value") + uploading from slave, and it works. If this version doesn't work for you, please, provide new stacktrace and example of metadata.

**Comment by peternijssen** [comment]
Great seeing this change being merged. Any chance a new version is tagged soon? Thanks!

**Comment by Jimilian** [comment]
@peternijssen I hope I just did it. It was my first plugin release ever, so, I'm not quite sure :)

**Comment by peternijssen** [comment]
Nice! It's not showing up yet in Jenkins, but it might take some time. I'll keep an eye on it today and will start using it this week. I'll let you know if I come across anything :) 

Thanks for stepping up to maintain this plugin. Really appreciated!

**Comment by STRML** [comment]
Sorry to piggyback on this - but without documentation, a Wiki, or an Issues section, I didn't see anywhere else to go. Does anyone have an example of using this with the Pipeline Plugin to archive a finished build & send it to S3?

**Comment by Jimilian** [comment]
Documentation doesn't make any sense, because with Snippet Generator (Step -> S3 Copy Artifacts) anyone can generate code for desired behavior. Some basic example:
`step([$class: 'S3CopyArtifact', buildSelector: [$class: 'SpecificBuildSelector', buildNumber: '123'], excludeFilter: 'ignore.txt', filter: '*.txt', flatten: true, optional: true, projectName: 'SomeBuild', target: 'install/'])`

**Comment by STRML** [comment]
Thanks - the key is the "step" step, which was unexpected to me. Perhaps
they will make that more clear in the future.

Also, there are two S3 steps defined - what is the difference?

**Comment by Jimilian** [comment]
@STRML , first one - to publish, second one - to download.

**Comment by STRML** [comment]
I see. Thanks a lot @Jimilian.

**Pull request merged**
