### PR TITLE
[JENKINS-29582] Avoid null buildselector

### PR DESCRIPTION
**Pull request by directhex**
copyartifact is heavily depended on for s3, including some use of internal jelly.

This changeset includes two changes - it normalises the jelly to match the style of current copyartifact, removing its custom namespace (which fixes the build selector missing from job configuration), and it adds a fallback buildselector in the event of null being passed (which is a better fallback than throwing a NPE, as is the current behaviour)

### CODE REVIEW

**Comment by directhex** [comment]
Build failure caused by https://github.com/jenkinsci/s3-plugin/pull/60 not being merged yet.

**Comment by rafaelmagu** [comment]
After this PR is merged, how quickly can we get a release out?

**Comment by alecharp** [comment]
It seems that the PR is not validated by the build. I cannot find the {{doFillAvailableBuildSelectorList}} which seems to require the {{config.jelly}}

**Comment by directhex** [comment]
Closing, as this is superceded by #77

**Pull request closed without merging**
