### PR TITLE
Add Pipeline usage snippet

### PR DESCRIPTION
**Pull request by davividal**
After a couple hours and a lot of source code reading, I managed to get this plugin working using Jenkinsfile.

So, I'm making this PR so other users won't struggle as much as I did.

### CODE REVIEW

**Comment by Jimilian** [comment]
Thanks for your PR!
@davividal , but what was wrong with Snippet Generator? Usually it provides enough information, even I was able to use it :)

**Comment by davividal** [comment]
@Jimilian actually, there was a problem in my browser and the Snippet Generator wasn't working.
Feel free to ignore this PR. :)

**Comment by Jimilian** [comment]
@davividal Sorry for that, but it would be hard to maintain your changes.

**Comment by bensquire** [comment]
@Jimilian This snippet proved very useful. For me, the snippet generator doesn't show the S3 plugin...

**Pull request closed without merging**
